### ISSUE TITLE
怎么用？

### ISSUE THREAD

**Issue by 284324096** [wangdoc/bash-tutorial#23]
你好， 偶是小白，不知道咋用啊？直接打开doc中的文件看吗？有没有其他方式？

**Comment by cydiacen** [comment]
点击项目描述的地址

**Comment by 284324096** [comment]
这个是怎么从https://github.com/wangdoc/bash-tutorial 到https://wangdoc.com/bash/的？是自己架设了web服务器吗？

**Comment by snow212-cn** [comment]
安装nodejs，执行npm run server，然后打开http://localhost:8080
