### ISSUE TITLE
网道web页目录不全，没有显示/docs/archives下的文件目录

### ISSUE THREAD

**Issue by caowent** [wangdoc/bash-tutorial#31]
比如想要查看文件操作命令rm的使用方法，在[网道web页](https://wangdoc.com/bash/)无法找到对应目录。但通过查找，可以在源码处看到相应的文档。

![wangdoc_directory](https://user-images.githubusercontent.com/37276994/85976203-8ad7e500-ba0c-11ea-8a80-b7bf2b8cf2ba.png)

**Comment by ruanyf** [comment]
那些是草稿存档，不会放在 Bash 教程里面。

后面打算出 Linux 教程，再把这些重写后加进去。
