### ISSUE TITLE
在mac15.5里的shell有些不一样

### ISSUE THREAD

**Issue by walt008** [wangdoc/bash-tutorial#34]
mac新版os使用zsh解析shell命令，数组foo=(a b c d e f) ,  foo[1] 表示第一个元素，foo[0]输出为空，echo ${foo}  是输出所以元素而不是第一个。
`walt@MacBook-Pro ~ % foo=(a b c d e f)
walt@MacBook-Pro ~ % echo ${foo}
a b c d e f
walt@MacBook-Pro ~ % echo ${foo[0]}

walt@MacBook-Pro ~ % echo ${foo[1]}
a`

**Comment by ruanyf** [comment]
这个教程就不涉及 zsh 了，只局限在 Bash，而且偏重服务器端的 Bash。
