### ISSUE TITLE
子字符串操作关于length的说明

### ISSUE THREAD

**Issue by gujing** [wangdoc/bash-tutorial#39]
在字符串操作章节的子字符串小节中关于length的说明

> 如果offset为负值，表示从字符串的末尾开始算起。注意，负数前面必须有一个空格， 以防止与${variable:-word}的变量的设置默认值语法混淆。这时，如果还指定length，则length不能小于零。

length其实是可以小于0的，但是不能比offset更小。这个时候的行为和python中字符串切片操作中效果是类似的。

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
