### ISSUE TITLE
bash教程中循环章节最后select示例的小小问题

### ISSUE THREAD

**Issue by HKCM** [wangdoc/bash-tutorial#43]
Hi

首先感谢网道提供的优秀文档。

在学习过程中发现了一个小小的问题
https://wangdoc.com/bash/loop.html#select-%E7%BB%93%E6%9E%84

select中选项为"Windows8 Windows7 WindowsXP"
case中选项为""Windows8" | "Windows10" | "WindowsXP")"
导致选择win7时意外退出

希望网道越来越好

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
