### ISSUE TITLE
大括号扩展篇幅中的问题

### ISSUE THREAD

**Issue by RopeHuo** [wangdoc/bash-tutorial#45]
https://wangdoc.com/bash/expansion.html#%E5%A4%A7%E6%8B%AC%E5%8F%B7%E6%89%A9%E5%B1%95

`echo {cat,d*}` 为什么会额外输出 `dawg dg dig dog doug dug` 呢？

**Comment by ruanyf** [comment]
这是假定这几个文件已经存在。

这里确实写得不清楚，我已经改掉了。
