### ISSUE TITLE
网页链接无法打开

### ISSUE THREAD

**Issue by techkang** [wangdoc/bash-tutorial#46]
https://wangdoc.com/bash/ 以及 wangdoc.com/bash/ 均无法打开

**Comment by ruanyf** [comment]
我用了 Cloudflare 作为免费 CDN，看来是墙的原因。

翻墙就好了，我看看明天是否会恢复正常。

**Comment by ruanyf** [comment]
确定被 DNA 劫持了，翻墙可以正常使用。打算明天再观察一下。

**Comment by xgqfrms** [comment]
> 确定被 DNA 劫持了，翻墙可以正常使用。打算明天再观察一下。

Typo: <del>DNA 劫持</del> => DNS劫持
