### ISSUE TITLE
grammar 中的 || 解释错了

### ISSUE THREAD

**Issue by bubao** [wangdoc/bash-tutorial#64]
>  ```bash
> Command1 || Command2
> ```
> 上面命令的意思是，如果`Command1`命令运行失败，则继续运行`Command2`命令。
> 引用自 [L155-L159](https://github.com/wangdoc/bash-tutorial/blob/cedfbe5b7f8e64495c2f49631d6e2d1074100b68/docs/grammar.md?plain=1#L155-L159)

应该是：不管`Command1`命令运行失败与否，`Command2`命令都会执行。

> ```bash
> $ mkdir foo || mkdir bar
> ```
> 上面例子中，只有`mkdir foo`命令执行失败（比如`foo`目录已经存在），才会继续执行`mkdir bar`命令。如果`mkdir foo`命令执行成功，就不会创建`bar`目录了
> 引用自 [#L175-L179](https://github.com/wangdoc/bash-tutorial/blob/cedfbe5b7f8e64495c2f49631d6e2d1074100b68/docs/grammar.md?plain=1#L175-L179)

应该是：即使`mkdir foo`命令执行失败，也会执行继续执行`mkdir bar`命令

例子

```sh
~/temp/mkdir-test 
➜ ls

~/temp/mkdir-test 
➜ mkdir foo             

~/temp/mkdir-test 
➜ ls
foo

~/temp/mkdir-test 
➜ mkdir foo || mkdir bar
mkdir: 无法创建目录 “foo”: 文件已存在

~/temp/mkdir-test 
➜ ls
bar  foo
```

**Comment by ruanyf** [comment]
command1 成功，command2 不会运行。
