### ISSUE TITLE
测试失败 [ -n string ]

### ISSUE THREAD

**Issue by cws999** [wangdoc/bash-tutorial#73]
https://wangdoc.com/bash/condition.html

此处测试失败`[ -n string ]：如果字符串string的长度大于零，则判断为真`
[[ -n string ]] 须要两个括号才行,我在devuan,bash下测试的

**Comment by Tommaker** [comment]
亲爱的朋友，很高兴收到你的邮件，谢谢！

**Comment by ruanyf** [comment]
原文没错。
