### ISSUE TITLE
一处笔误

### ISSUE THREAD

**Issue by lilucpp** [wangdoc/bash-tutorial#79]
老师你好，发现了一处笔误。
[模式扩展-start-end-扩展](https://github.com/wangdoc/bash-tutorial/blob/master/docs/expansion.md#start-end-%E6%89%A9%E5%B1%95)中一处示例的`echo`本意应该是`ls`。
```txt
$ echo report[!1–3].txt
report4.txt report5.txt
```
修改为
```txt
$ ls report[!1–3].txt
report4.txt report5.txt
```

**Comment by Tommaker** [comment]
亲爱的朋友，很高兴收到你的邮件，谢谢！

**Comment by ruanyf** [comment]
这里 echo 和 ls 一样的。

**Comment by Tommaker** [comment]
亲爱的朋友，很高兴收到你的邮件，谢谢！
