### ISSUE TITLE
3种条件判断方式的思考

### ISSUE THREAD

**Issue by jimgreen2013** [wangdoc/bash-tutorial#82]
阮老师好，大家好:

  我对[条件判断](https://wangdoc.com/bash/condition#%E6%99%AE%E9%80%9A%E5%91%BD%E4%BB%A4%E7%9A%84%E9%80%BB%E8%BE%91%E8%BF%90%E7%AE%97)这篇的几个小建议，但我也是shell新手，不确定以下的建议是否合理。

1. 差异
`[`和`[[`的差异还是很多的，建议将第2小节开头介绍的句子
> 上面三种形式是等价的，但是第三种形式还支持正则判断，前两种不支持。

修改为

> 上面三种形式是等价的，主要的差异是前两种是POSIX的标准`test`命令，第三种是bash的扩展语法，它的表达式语法更接近一般的高级语言，甚至支持正则判断

2.  `test` 例子优化
3.5小节在讨论*test 判断的逻辑运算*，最后举的例子是

```bash
if [ ! \( $INT -ge $MIN_VAL -a $INT -le $MAX_VAL \) ]; then
    echo "$INT is outside $MIN_VAL to $MAX_VAL."
else
    echo "$INT is in range."
fi
```

这里通过`-a`选项来表达`且`已经不被[POXIS](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html)推荐了, 原文如下：

>  That is, in cases where maximal portability is of concern, replace:
>
> test expr1 -a expr2
> 
> with:
> 
> test expr1 && test expr2
> 

所以例子最好也采用标准推荐的写法

```bash
if !  (  [ $INT -ge $MIN_VAL ] && [ $INT -le $MAX_VAL ]  ); then
    echo "$INT is outside $MIN_VAL to $MAX_VAL."
else
    echo "$INT is in range."
fi
```

3. 是否有必要列举`[`和`[[`的全部差异？

**Comment by Tommaker** [comment]
亲爱的朋友，很高兴收到你的邮件，谢谢！

**Comment by ruanyf** [comment]
我改了一下第2点，至于`[`与`[[`的详细差异，以后再补充吧。
